---
- name: First Play - Docker Image Build
  hosts: docker
  tasks:
    - name: Copy Dockerfile
      copy:
       src: Dockerfile
       dest: /home/sreejith/
    - name: Copy Artifact
      copy:
       src: target
       dest: /home/sreejith
    - name : Build image
      command: docker build -t nexus.openhelp.net/docker-private/sreejith/mavenwebapp .
    - name : Push Docker Image
      command: docker push nexus.openhelp.net/docker-private/sreejith/mavenwebapp
- name: Second Play - K8s Deployment
  hosts: eks
  tasks:
   - name: 
     copy:
       src: k8s-deploy.yml
       dest: /home/sreejith
   - name : K8S Deployment
     command: kubectl apply -f k8s-deploy.yml
